package: minify_images
version: '2.0.0-dev'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/minify_images

page:
    title: 'translate:title'
    perm: minify_images[]
    pjax: true
    subpages:
        config: { title: 'translate:config', perm: minify_images[config] }
        readme: { title: translate:readme, subPath: README.md }

requires:
    redaxo: '^5.1'
